[package]
name = "bian-proc"
version = "0.2.0"
authors = ["PrivateRookie <996514515@qq.com>"]
edition = "2018"
description = "proc used by bian-rs"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
